version = 0.1
[default.deploy.parameters]
stack_name = "simple-node-prod"
s3_bucket = "my-sam-artifacts-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=prod"
